\c uin_checker

CREATE TABLE contractor
(
    inn  VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_contractor PRIMARY KEY (inn)
);

CREATE TABLE jewelry_item
(
    uin            VARCHAR(16)  NOT NULL,
    description    VARCHAR(500) NOT NULL,
    article_number VARCHAR(50)  NOT NULL,
    is_sold        BOOLEAN      NOT NULL,
    shop_id        BIGINT       NOT NULL,
    seller_id      VARCHAR(255),
    sold_date      TIMESTAMP,
    CONSTRAINT pk_jewelry_item PRIMARY KEY (uin)
);

CREATE TABLE request_history
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uin            VARCHAR(16)                             NOT NULL,
    request_date   TIMESTAMP                               NOT NULL,
    status         VARCHAR(255)                            NOT NULL,
    response_data  text,
    source         VARCHAR(50),
    request_data   text                             NOT NULL,
    timestamp      TIMESTAMP                               NOT NULL,
    failed_checked BOOLEAN                                 NOT NULL,
    duration       BIGINT                                  NOT NULL,
    captcha_path   text,
    captcha_text   text,
    CONSTRAINT pk_request_history PRIMARY KEY (id)
);

CREATE TABLE shop
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address       VARCHAR(255)                            NOT NULL,
    contractor_id VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_shop PRIMARY KEY (id)
);

ALTER TABLE jewelry_item
    ADD CONSTRAINT uc_jewelry_item_articlenumber UNIQUE (article_number);

ALTER TABLE jewelry_item
    ADD CONSTRAINT FK_JEWELRY_ITEM_ON_SELLER FOREIGN KEY (seller_id) REFERENCES contractor (inn);

ALTER TABLE jewelry_item
    ADD CONSTRAINT FK_JEWELRY_ITEM_ON_SHOP FOREIGN KEY (shop_id) REFERENCES shop (id);

ALTER TABLE shop
    ADD CONSTRAINT FK_SHOP_ON_CONTRACTOR FOREIGN KEY (contractor_id) REFERENCES contractor (inn);